/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicascrum;

import Clases.Transaccion;
import Clases.TransaccionCE;
import Clases.TransaccionEESE;
import Clases.TransaccionFLIFLE;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class AnadirTransaccion extends javax.swing.JFrame {

    /**
     * Creates new form AnadirTransaccion
     */
    public AnadirTransaccion() {
        initComponents();
        this.setTitle("Cálculo Punto Función");
        jPanel1_FLIFLE.setVisible(true);
        jPanel1_CE.setVisible(false);
        jPanel1_EEEISE.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2_Name = new javax.swing.JLabel();
        jTextField1_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1_Tipo = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1_FLIFLE = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1_DET = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner2_RET = new javax.swing.JSpinner();
        jPanel1_EEEISE = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1_DET1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2_RET1 = new javax.swing.JSpinner();
        jPanel1_CE = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1_DET2 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner2_RET2 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1_DET3 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner2_RET3 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1_Añadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("AÑADIR TRANSACCIÓN");

        jLabel2_Name.setText("Nombre:");

        jTextField1_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_NameActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo: ");

        jComboBox1_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FLI", "FLE", "EE", "SE", "CE" }));
        jComboBox1_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_TipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nº datos elementales:");

        jLabel4.setText("Nº de registros:");

        javax.swing.GroupLayout jPanel1_FLIFLELayout = new javax.swing.GroupLayout(jPanel1_FLIFLE);
        jPanel1_FLIFLE.setLayout(jPanel1_FLIFLELayout);
        jPanel1_FLIFLELayout.setHorizontalGroup(
            jPanel1_FLIFLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FLIFLELayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1_FLIFLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1_FLIFLELayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner2_RET, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_FLIFLELayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1_DET, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1_FLIFLELayout.setVerticalGroup(
            jPanel1_FLIFLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_FLIFLELayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1_FLIFLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1_DET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1_FLIFLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner2_RET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1_EEEISE.setPreferredSize(new java.awt.Dimension(260, 135));

        jLabel5.setText("Nº datos elementales:");

        jLabel6.setText("Nº  Ficheros referenciados:");

        javax.swing.GroupLayout jPanel1_EEEISELayout = new javax.swing.GroupLayout(jPanel1_EEEISE);
        jPanel1_EEEISE.setLayout(jPanel1_EEEISELayout);
        jPanel1_EEEISELayout.setHorizontalGroup(
            jPanel1_EEEISELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_EEEISELayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1_EEEISELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1_EEEISELayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner2_RET1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1_EEEISELayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(jSpinner1_DET1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 83, Short.MAX_VALUE))
        );
        jPanel1_EEEISELayout.setVerticalGroup(
            jPanel1_EEEISELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_EEEISELayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1_EEEISELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1_DET1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1_EEEISELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2_RET1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1_CE.setPreferredSize(new java.awt.Dimension(260, 135));
        jPanel1_CE.setRequestFocusEnabled(false);

        jLabel7.setText("Nº datos elementales:");

        jLabel8.setText("Nº Ficheros referenciados:");

        jLabel9.setText("Nº datos elementales:");

        jLabel10.setText("Nº Ficheros referenciados:");

        jLabel11.setText("ENTRADA");

        jLabel12.setText("SALIDA");

        javax.swing.GroupLayout jPanel1_CELayout = new javax.swing.GroupLayout(jPanel1_CE);
        jPanel1_CE.setLayout(jPanel1_CELayout);
        jPanel1_CELayout.setHorizontalGroup(
            jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_CELayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1_CELayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner2_RET2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1_CELayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner2_RET3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1_CELayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1_DET2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1_CELayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(53, 53, 53)
                            .addComponent(jSpinner1_DET3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        jPanel1_CELayout.setVerticalGroup(
            jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_CELayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner1_DET2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1_DET3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinner2_RET2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1_CELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner2_RET3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1_FLIFLE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1_EEEISE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel1_CE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_CE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1_EEEISE, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1_FLIFLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1_EEEISE, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1_FLIFLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        jButton1_Añadir.setText("Añadir");
        jButton1_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1_Añadir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel2_Name)
                            .addGap(12, 12, 12)
                            .addComponent(jTextField1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(jLabel2)
                            .addGap(6, 6, 6)
                            .addComponent(jComboBox1_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_Name)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_Añadir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_NameActionPerformed

    private void jComboBox1_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_TipoActionPerformed
        // COMBO BOX DE OPC 
        if (jComboBox1_Tipo.getSelectedItem().toString().equals("FLI") || jComboBox1_Tipo.getSelectedItem().toString().equals("FLE")) {
            jPanel1_FLIFLE.setVisible(true);
            jPanel1_CE.setVisible(false);
            jPanel1_EEEISE.setVisible(false);
        } else if (jComboBox1_Tipo.getSelectedItem().toString().equals("EE") || jComboBox1_Tipo.getSelectedItem().toString().equals("SE")) {
            jPanel1_FLIFLE.setVisible(false);
            jPanel1_CE.setVisible(false);
            jPanel1_EEEISE.setVisible(true);
        } else {
            jPanel1_FLIFLE.setVisible(false);
            jPanel1_CE.setVisible(true);
            jPanel1_EEEISE.setVisible(false);
        }


    }//GEN-LAST:event_jComboBox1_TipoActionPerformed

    private void jButton1_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AñadirActionPerformed
        // VALIDACION TRANSACCION
        String nombre = jTextField1_Name.getText();
        String tipo = jComboBox1_Tipo.getSelectedItem().toString();

        if (jComboBox1_Tipo.getSelectedItem().toString().equals("FLI") || jComboBox1_Tipo.getSelectedItem().toString().equals("FLE")) {
            //COMPRUEBO FLI FLE
            Integer DET = Integer.parseInt(jSpinner1_DET.getValue().toString());
            Integer RET = Integer.parseInt(jSpinner2_RET.getValue().toString());

            if (!nombre.equals("") && DET > 0 && RET >= 0) {
                if (!MainFrame.existeTransaccion(nombre)) {
                    TransaccionFLIFLE t = new TransaccionFLIFLE(nombre, tipo, DET, RET);
                    MainFrame.transacciones.add(t);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error, ya existe otra transaccion con el mismo nombre");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al introducir la transacción");
            }
        } else if (jComboBox1_Tipo.getSelectedItem().toString().equals("EE") || jComboBox1_Tipo.getSelectedItem().toString().equals("SE")) {
            //COMPRUEBO EE EI
            Integer DET = Integer.parseInt(jSpinner1_DET1.getValue().toString());
            Integer RET = Integer.parseInt(jSpinner2_RET1.getValue().toString());

            if (!nombre.equals("") && DET > 0 && RET >= 0) {
                if (!MainFrame.existeTransaccion(nombre)) {
                    TransaccionEESE t = new TransaccionEESE(nombre, tipo, DET, RET);
                    MainFrame.transacciones.add(t);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error, ya existe otra transaccion con el mismo nombre");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al introducir la transacción");
            }

        } else {
            //COMPRUEBO CE
            Integer EntradaDET = Integer.parseInt(jSpinner1_DET2.getValue().toString());
            Integer EntradaRET = Integer.parseInt(jSpinner1_DET3.getValue().toString());

            Integer SalidaDET = Integer.parseInt(jSpinner2_RET2.getValue().toString());
            Integer SALIDARET = Integer.parseInt(jSpinner2_RET3.getValue().toString());

            if (!nombre.equals("") && EntradaDET > 0 && EntradaRET >= 0 && SalidaDET > 0 && SALIDARET >= 0) {
                if (!MainFrame.existeTransaccion(nombre)) {
                    TransaccionCE t = new TransaccionCE(nombre, tipo, EntradaDET, EntradaRET, SalidaDET, SALIDARET);
                    MainFrame.transacciones.add(t);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error, ya existe otra transaccion con el mismo nombre");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al introducir la transacción");
            }
        }
        //SETEO DE LOS VALORES A DEFAULT
        jTextField1_Name.setText("");
        jComboBox1_Tipo.setSelectedIndex(0);

        //TODOS LOS CAMPOS A 0
        jSpinner1_DET.setValue(0);
        jSpinner1_DET1.setValue(0);
        jSpinner2_RET.setValue(0);
        jSpinner1_DET2.setValue(0);
        jSpinner1_DET3.setValue(0);
        jSpinner2_RET2.setValue(0);
        jSpinner2_RET3.setValue(0);
        
        
        //LLAMAMOS AL METODO CALCULAR TODO DEL MAINFRAME
        MainFrame.calcula();
    }//GEN-LAST:event_jButton1_AñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirTransaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Añadir;
    private javax.swing.JComboBox<String> jComboBox1_Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Name;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1_CE;
    private javax.swing.JPanel jPanel1_EEEISE;
    private javax.swing.JPanel jPanel1_FLIFLE;
    private javax.swing.JSpinner jSpinner1_DET;
    private javax.swing.JSpinner jSpinner1_DET1;
    private javax.swing.JSpinner jSpinner1_DET2;
    private javax.swing.JSpinner jSpinner1_DET3;
    private javax.swing.JSpinner jSpinner2_RET;
    private javax.swing.JSpinner jSpinner2_RET1;
    private javax.swing.JSpinner jSpinner2_RET2;
    private javax.swing.JSpinner jSpinner2_RET3;
    private javax.swing.JTextField jTextField1_Name;
    // End of variables declaration//GEN-END:variables
}
