/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicascrum;

/**
 *
 * @author Carlos
 */
public class CalculoEsfuerzoDuracion extends javax.swing.JFrame {

    //Esfuerzo
    Double MF_C = 49.02; Double MF_E = 0.736;
    Double MR_C = 78.88; Double MR_E = 0.646;
    Double PC_C = 48.9; Double PC_E = 0.661;
    Double Multi_C = 16.01; Double Multi_E = 0.865;
    Double _3GL_C = 54.65; Double _3GL_E = 0.717;
    Double _4GL_C = 29.5; Double _4GL_E = 0.758;
    Double GenAp_C = 68.11; Double GenAp_E = 0.660;
    Double Mantenimiento_C = 52.58; Double Mantenimiento_E = 0.683;
    Double Nuevo_C = 39.05; Double Nuevo_E = 0.731;
    Double MF_3GL_C = 65.37; Double MF_3GL_E = 0.705;
    Double MF_4GL_C = 52.09; Double MF_4GL_E = 0.640;
    Double MF_GenAp_C = 65.68; Double MF_GenAp_E = 0.692;
    Double MR_3GL_C = 126.3; Double MR_3GL_E = 0.565;
    Double MR_4GL_C = 62.35; Double MR_4GL_E = 0.694;
    Double PC_3GL_C = 60.46; Double PC_3GL_E = 0.648;
    Double PC_4GL_C = 36.48; Double PC_4GL_E = 0.694;
    Double Multi_3GL_C = 19.82; Double Multi_3GL_E = 0.666;
    Double Multi_4GL_C = 6.49; Double Multi_4GL_E = 0.983;
    Double MF_3GL_Mantenimiento_C = 83.27; Double MF_3GL_Mantenimiento_E = 0.650;
    
    
    //Duracion
    Double Duracion_PC_C = 0.503; Double Duracion_PC_E = 0.409;
    Double Duracion_Multi_C = 0.679; Double Duracion_Multi_E = 0.341;
    Double Duracion_4GL_C = 0.578; Double Duracion_4GL_E = 0.393;
    Double Duracion_Nuevo_C = 0.739; Double Duracion_Nuevo_E = 0.359;
    Double Duracion_PC_4GL_C = 0.348; Double Duracion_PC_4GL_E = 0.471;
    Double Duracion_Multi_4GL_C = 0.366; Double Duracion_Multi_4GL_E = 0.451;
    Double Duracion_PC_4GL_Nuevo_C = 0.250; Double Duracion_PC_4GL_Nuevo_E = 0.515;
    Double Duracion_Multi_4GL_Nuevo_C = 0.240; Double Duracion_Multi_4GL_Nuevo_E = 0.518;
    Double Duracion_Otro_C = 0.411; Double Duracion_Otro_E = 0.328;
    /**
     * Creates new form CalculoEsfuerzoDuracion
     */
    public CalculoEsfuerzoDuracion() {
        initComponents();
        this.setTitle("Cálculo Punto Función");
        
        Double esfuerzo = calculoEsfuerzo(jComboBox2.getSelectedItem().toString(), MainFrame.PFA);
        esfuerzo = Math.round(esfuerzo*100.0)/100.0;
        jLabel5.setText(esfuerzo.toString());
        
        Double duracion = calculoDuracion(jComboBox1.getSelectedItem().toString(), MainFrame.PFA);
        duracion = Math.round(duracion*100.0)/100.0;
        jLabel6.setText(duracion.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ESFUERZO");

        jLabel2.setText("Tipo de proyecto: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Multi", "4GL", "Nuevo", "PC_4GL", "Multi_4GL", "PC_4GL_Nuevo", "Multi_4GL_Nuevo", "Otro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Esfuerzo: ");

        jLabel4.setText("Duración:");

        jLabel7.setText("horas");

        jLabel8.setText("horas");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DURACIÓN");

        jLabel10.setText("Tipo de proyecto: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MF", "MR", "PC", "Multi", "3GL", "4GL", "GenAp", "Mantenimiento", "Nuevo", "MF_3GL", "MF_4GL", "MF_GenAp", "MR_3GL", "MR_4GL", "PC_3GL", "PC_4GL", "Multi_3GL", "Multi_4GL", "MF_3GL_Mantenimiento" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        Double esfuerzo = calculoEsfuerzo(jComboBox2.getSelectedItem().toString(), MainFrame.PFA);
        esfuerzo = Math.round(esfuerzo*100.0)/100.0;
        jLabel5.setText(esfuerzo.toString());        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Double duracion = calculoDuracion(jComboBox1.getSelectedItem().toString(), MainFrame.PFA);
        duracion = Math.round(duracion*100.0)/100.0;
        jLabel6.setText(duracion.toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoEsfuerzoDuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoEsfuerzoDuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoEsfuerzoDuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoEsfuerzoDuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoEsfuerzoDuracion().setVisible(true);
            }
        });
    }
    
    public Double calculoEsfuerzo(String tipo,Double PF){
        double esfuerzo=0;
        
        switch(tipo){
            case "MF":
                esfuerzo = MF_C * Math.pow(PF, MF_E);
                break;   
            case "MR":
                esfuerzo = MR_C * Math.pow(PF, MR_E);
                break;
            case "PC":
                esfuerzo = PC_C * Math.pow(PF, PC_E);
                break; 
            case "Multi":
                esfuerzo = Multi_C * Math.pow(PF, Multi_E);
                break;
            case "3GL":
                esfuerzo = _3GL_C * Math.pow(PF, _3GL_E);
                break; 
            case "4GL":
                esfuerzo = _4GL_C * Math.pow(PF, _4GL_E);
                break;
            case "GenAp":
                esfuerzo = GenAp_C * Math.pow(PF, GenAp_E);
                break;
            case "Mantenimiento":
                esfuerzo = Mantenimiento_C * Math.pow(PF, Mantenimiento_E);
                break;
            case "Nuevo":
                esfuerzo = Nuevo_C * Math.pow(PF, Nuevo_E);
                break;
            case "MF_3GL":
                esfuerzo = MF_3GL_C * Math.pow(PF, MF_3GL_E);
                break;
            case "MF_4GL":
                esfuerzo = MF_4GL_C * Math.pow(PF, MF_4GL_E);
                break;
            case "MF_GenAp":
                esfuerzo = MF_GenAp_C * Math.pow(PF, MF_GenAp_E);
                break;
            case "MR_3GL":
                esfuerzo = MR_3GL_C * Math.pow(PF, MR_3GL_E);
                break;
            case "MR_4GL":
                esfuerzo = MR_4GL_C * Math.pow(PF, MR_4GL_E);
                break;
            case "PC_3GL":
                esfuerzo = PC_3GL_C * Math.pow(PF, PC_3GL_E);
                break;
            case "PC_4GL":
                esfuerzo = PC_4GL_C * Math.pow(PF, PC_4GL_E);
                break;
            case "Multi_3GL":
                esfuerzo = Multi_3GL_C * Math.pow(PF, Multi_3GL_E);
                break;
            case "Multi_4GL":
                esfuerzo = Multi_4GL_C * Math.pow(PF, Multi_4GL_E);
                break;
            case "MF_3GL_Mantenimiento":
                esfuerzo = MF_3GL_Mantenimiento_C * Math.pow(PF, MF_3GL_Mantenimiento_E);
                break;       
        }
        return esfuerzo;
    }
    
    public Double calculoDuracion(String tipo, Double PF){
        double duracion=0;
        
        switch(tipo){
            case "PC":
                duracion = Duracion_PC_C * Math.pow(PF, Duracion_PC_E);
                break; 
            case "Multi":
                duracion = Duracion_Multi_C * Math.pow(PF, Duracion_Multi_E);
                break;
            case "4GL":
                duracion = Duracion_4GL_C * Math.pow(PF, Duracion_4GL_E);
                break;
            case "Nuevo":
                duracion = Duracion_Nuevo_C * Math.pow(PF, Duracion_Nuevo_E);
                break;
            case "PC_4GL":
                duracion = Duracion_PC_4GL_C * Math.pow(PF, Duracion_PC_4GL_E);
                break;
            case "Multi_4GL":
                duracion = Duracion_Multi_4GL_C * Math.pow(PF, Duracion_Multi_4GL_E);
                break;
            case "PC_4GL_Nuevo":
                duracion = Duracion_PC_4GL_Nuevo_C * Math.pow(PF, Duracion_PC_4GL_Nuevo_E);
                break;  
            case "Multi_4GL_Nuevo":
                duracion = Duracion_Multi_4GL_Nuevo_C * Math.pow(PF, Duracion_Multi_4GL_Nuevo_E);
                break; 
            default:
                duracion = Duracion_Otro_C * Math.pow(PF, Duracion_Otro_E);
                break; 
               
        }
        return duracion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
