/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicascrum;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos
 */
public class IdentificarInfluencia extends javax.swing.JFrame {

    /**
     * Creates new form IdentificarInfluencia
     */
    
    public IdentificarInfluencia() {
        initComponents();
        this.setTitle("Cálculo Punto Función");   
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19_SUMA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("IDENTIFICAR INFLUENCIAS");

        jLabel2.setText("ATRIBUTOS");

        jLabel3.setText("1. Comunicación de datos");

        jLabel4.setText("2. Funciones distribuidas");

        jLabel5.setText("3. Prestaciones");

        jLabel6.setText("4. Gran uso de la configuración");

        jLabel7.setText("5. Velocidad de las transacciones");

        jLabel8.setText("6. Entrada de datos en línea");

        jLabel9.setText("7. Diseño para la eficiencia del usuario final");

        jLabel10.setText("8. Actualización de datos en línea");

        jLabel11.setText("9. Complejidad del proceso lógico interno de la aplicación");

        jLabel12.setText("10. Reusabilidad del código");

        jLabel13.setText("11. Facilidad de instalación");

        jLabel14.setText("12. Facilidad de operación");

        jLabel15.setText("13. Localizaciones múltiples");

        jLabel16.setText("14. Facilidad de cambios");

        jLabel17.setText("INFLUENCIA");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });

        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });

        jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner6StateChanged(evt);
            }
        });

        jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner7StateChanged(evt);
            }
        });

        jSpinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner8StateChanged(evt);
            }
        });

        jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner9StateChanged(evt);
            }
        });

        jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner10StateChanged(evt);
            }
        });

        jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner11StateChanged(evt);
            }
        });

        jSpinner12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner12StateChanged(evt);
            }
        });

        jSpinner13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner13StateChanged(evt);
            }
        });

        jSpinner14.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner14StateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("SUMA");

        jLabel19_SUMA.setText("0");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel11))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19_SUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jSpinner9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jSpinner7)
                                    .addComponent(jSpinner6)
                                    .addComponent(jSpinner5)
                                    .addComponent(jSpinner4)
                                    .addComponent(jSpinner3)
                                    .addComponent(jSpinner2)
                                    .addComponent(jSpinner1)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(223, 223, 223)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner14)
                                    .addComponent(jSpinner13)
                                    .addComponent(jSpinner12)
                                    .addComponent(jSpinner11)
                                    .addComponent(jSpinner10))))))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19_SUMA))
                .addGap(20, 20, 20))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Sin Influencia"},
                {"1", "Influencia mínima"},
                {"2", "Influencia moderada"},
                {"3", "Influencia apreciable"},
                {"4", "Influencia significativa"},
                {"5", "Influencia muy fuerte"}
            },
            new String [] {
                "", "Influencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(20);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        if(Integer.parseInt(jSpinner1.getValue().toString())<0){
            jSpinner1.setValue(0);
        }else if(Integer.parseInt(jSpinner1.getValue().toString())>5){
            jSpinner1.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        if(Integer.parseInt(jSpinner2.getValue().toString())<0){
            jSpinner2.setValue(0);
        }else if(Integer.parseInt(jSpinner2.getValue().toString())>5){
            jSpinner2.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        if(Integer.parseInt(jSpinner3.getValue().toString())<0){
            jSpinner3.setValue(0);
        }else if(Integer.parseInt(jSpinner3.getValue().toString())>5){
            jSpinner3.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        if(Integer.parseInt(jSpinner4.getValue().toString())<0){
            jSpinner4.setValue(0);
        }else if(Integer.parseInt(jSpinner4.getValue().toString())>5){
            jSpinner4.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        if(Integer.parseInt(jSpinner5.getValue().toString())<0){
            jSpinner5.setValue(0);
        }else if(Integer.parseInt(jSpinner5.getValue().toString())>5){
            jSpinner5.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner5StateChanged

    private void jSpinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner6StateChanged
        if(Integer.parseInt(jSpinner6.getValue().toString())<0){
            jSpinner6.setValue(0);
        }else if(Integer.parseInt(jSpinner6.getValue().toString())>5){
            jSpinner6.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner6StateChanged

    private void jSpinner7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner7StateChanged
        if(Integer.parseInt(jSpinner7.getValue().toString())<0){
            jSpinner7.setValue(0);
        }else if(Integer.parseInt(jSpinner7.getValue().toString())>5){
            jSpinner7.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner7StateChanged

    private void jSpinner8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner8StateChanged
        if(Integer.parseInt(jSpinner8.getValue().toString())<0){
            jSpinner8.setValue(0);
        }else if(Integer.parseInt(jSpinner8.getValue().toString())>5){
            jSpinner8.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner8StateChanged

    private void jSpinner9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner9StateChanged
        if(Integer.parseInt(jSpinner9.getValue().toString())<0){
            jSpinner9.setValue(0);
        }else if(Integer.parseInt(jSpinner9.getValue().toString())>5){
            jSpinner9.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner9StateChanged

    private void jSpinner10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner10StateChanged
        if(Integer.parseInt(jSpinner10.getValue().toString())<0){
            jSpinner10.setValue(0);
        }else if(Integer.parseInt(jSpinner10.getValue().toString())>5){
            jSpinner10.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner10StateChanged

    private void jSpinner11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner11StateChanged
        if(Integer.parseInt(jSpinner11.getValue().toString())<0){
            jSpinner11.setValue(0);
        }else if(Integer.parseInt(jSpinner11.getValue().toString())>5){
            jSpinner11.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner11StateChanged

    private void jSpinner12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner12StateChanged
        if(Integer.parseInt(jSpinner12.getValue().toString())<0){
            jSpinner12.setValue(0);
        }else if(Integer.parseInt(jSpinner12.getValue().toString())>5){
            jSpinner12.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner12StateChanged

    private void jSpinner13StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner13StateChanged
        if(Integer.parseInt(jSpinner13.getValue().toString())<0){
            jSpinner13.setValue(0);
        }else if(Integer.parseInt(jSpinner13.getValue().toString())>5){
            jSpinner13.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner13StateChanged

    private void jSpinner14StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner14StateChanged
        if(Integer.parseInt(jSpinner14.getValue().toString())<0){
            jSpinner14.setValue(0);
        }else if(Integer.parseInt(jSpinner14.getValue().toString())>5){
            jSpinner14.setValue(5);
        }
        Integer suma = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        jLabel19_SUMA.setText(suma.toString());
    }//GEN-LAST:event_jSpinner14StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // GUARDAR LA INFLUENCIA
        MainFrame.SVA = Integer.parseInt(jSpinner1.getValue().toString())+Integer.parseInt(jSpinner2.getValue().toString())+Integer.parseInt(jSpinner3.getValue().toString())+Integer.parseInt(jSpinner4.getValue().toString())+Integer.parseInt(jSpinner5.getValue().toString())+Integer.parseInt(jSpinner6.getValue().toString())+Integer.parseInt(jSpinner7.getValue().toString())+Integer.parseInt(jSpinner8.getValue().toString())+Integer.parseInt(jSpinner9.getValue().toString())+
                Integer.parseInt(jSpinner10.getValue().toString())+Integer.parseInt(jSpinner11.getValue().toString())+Integer.parseInt(jSpinner12.getValue().toString())+Integer.parseInt(jSpinner13.getValue().toString())+Integer.parseInt(jSpinner14.getValue().toString());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdentificarInfluencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdentificarInfluencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdentificarInfluencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdentificarInfluencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdentificarInfluencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19_SUMA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
