/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicascrum;

import Clases.Transaccion;
import Clases.TransaccionCE;
import Clases.TransaccionEESE;
import Clases.TransaccionFLIFLE;
import javax.swing.table.DefaultTableModel;
import practicascrum.MainFrame;

/**
 *
 * @author Carlos
 */
public class MostrarComplejidad extends javax.swing.JFrame {

    DefaultTableModel dtm;

    /**
     * Creates new form MostrarComplejidad
     */
    public MostrarComplejidad() {
        initComponents();
        this.setTitle("Cálculo Punto Función");

    }

    public void actualizaTabla() {
        dtm = (DefaultTableModel) jTable1.getModel();
        
        dtm.setRowCount(0);
        
        for (int i = 0; i < MainFrame.transacciones.size(); i++) {
            Transaccion t = MainFrame.transacciones.get(i);
            dtm.addRow(new Object[]{t.getNombre(), t.getTipo(), calculaComplejidad(t)});
        }
    }
    
    public static String calculaComplejidad(Transaccion t) {

        if (t.getTipo().equals("FLI") || t.getTipo().equals("FLE")) {
            //FLI FLE
            TransaccionFLIFLE aux = (TransaccionFLIFLE) t;
            int DET = aux.getDET();
            int RET = aux.getRET();

            if ((DET < 50 && RET == 1) || (RET > 1 && RET < 6 && DET < 20)) {
                return "Sencilla";
            } else if ((DET > 51 && RET == 1) || (RET > 1 && RET < 6 && DET > 20 && DET < 51) || (RET > 5 && DET < 20)) {
                return "Media";
            } else {
                return "Compleja";
            }
        } else if (t.getTipo().equals("EE") || t.getTipo().equals("SE")) {
            //EE SE
            TransaccionEESE aux = (TransaccionEESE) t;
            int DET = aux.getDET();
            int RET = aux.getFicherosReferenciados();

            if ((DET < 16 && RET < 2) || (RET == 2 && DET < 5)) {
                return "Sencilla";
            } else if ((DET > 16 && RET < 2) || (RET == 2 && DET > 4 && DET < 16) || (RET > 2 && DET < 5)) {
                return "Media";
            } else {
                return "Compleja";
            }

        } else {
            //CE
            TransaccionCE aux = (TransaccionCE) t;

            Transaccion entrada = new TransaccionEESE("entrada", "EE", aux.getEntradaDET(), aux.getEntradaFicherosReferenciados());
            Transaccion salida = new TransaccionEESE("salida", "SE", aux.getSalidaDET(), aux.getSalidaFicherosReferenciados());

            String complejidadE = calculaComplejidad(entrada);
            String complejidadS = calculaComplejidad(salida);

            if (complejidadE.equals(complejidadS)) {
                return complejidadE;
            } else {
                if ((complejidadE.equals("Sencilla") && complejidadS.equals("Media")) || (complejidadE.equals("Media") && complejidadS.equals("Sencilla"))) {
                    return "Media";
                } else {
                    return "Compleja";
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transacción", "Tipo", "Complejidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("COMPLEJIDADES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarComplejidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MostrarComplejidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
